version: "3.3"
services:
  bot:
    image: chay-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chay-bot
    restart: unless-stopped
    volumes:
      - chay-bot-data:/app/data

volumes:
  chay-bot-data:
